name: Run Python Script

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때 트리거

jobs:
  run:
    runs-on: windows-latest  # Windows 환경에서 실행

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 사용할 Python 버전

    - name: Run the Python script
      run: python divisors.py 100   # 실행할 Python 스크립트 경로
